In [21]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
con=np.concatenate((arr,arr1),axis=0) 
#concatenating two arrays
print('concatenating with axis 0')
print(con)


concatenating with axis 0
[1 2 3 4 5 6]


In [55]:
import numpy as np
arr=np.array([[1,2,3],[1,2,3,]])
arr1=np.array([[4,5,6],[2,3,4]])
arr2=np.concatenate((arr,arr1),axis=1) 
#concatenating two arrays
print('concatenating with axis 1')
print(arr2)


concatenating of two arrays
[[1 2 3 4 5 6]
 [1 2 3 2 3 4]]


In [13]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
con=np.concatenate((arr,arr1)) 
#concatenating two arrays
print('concatenating of two arrays')
print(con)


concatenating of two arrays
[1 2 3 4 5 6]


In [7]:
import numpy as np
data1=np.array([2,6,4,10])
print("/n reverse of array")
rev=np.flip(data1)
print(rev)


/n reverse of array
[10  4  6  2]
